# Map user-friendly language names to canonical language codes used by STT/TTS
LANGUAGE_MAP = {
    "Afrikaans": "af-ZA",
    "Albanian": "sq-AL",
    "Amharic": "am-ET",
    "Arabic": "ar-XA",
    "Armenian": "hy-AM",
    "Basque": "eu-ES",
    "Bengali": "bn-IN",
    "Bulgarian": "bg-BG",
    "Catalan": "ca-ES",
    "Chinese": "cmn-CN",
    "Cantonese": "yue-HK",
    "Croatian": "hr-HR",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Dutch": "nl-NL",
    "English": "en-US",
    "Estonian": "et-EE",
    "Filipino": "fil-PH",
    "Finnish": "fi-FI",
    "French": "fr-FR",
    "Galician": "gl-ES",
    "Georgian": "ka-GE",
    "German": "de-DE",
    "Greek": "el-GR",
    "Gujarati": "gu-IN",
    "Hebrew": "he-IL",
    "Hindi": "hi-IN",
    "Hungarian": "hu-HU",
    "Icelandic": "is-IS",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Kannada": "kn-IN",
    "Khmer": "km-KH",
    "Korean": "ko-KR",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Macedonian": "mk-MK",
    "Malay": "ms-MY",
    "Malayalam": "ml-IN",
    "Marathi": "mr-IN",
    "Nepali": "ne-NP",
    "Norwegian": "nb-NO",
    "Persian": "fa-IR",
    "Polish": "pl-PL",
    "Portuguese": "pt-BR",
    "Punjabi": "pa-IN",
    "Romanian": "ro-RO",
    "Russian": "ru-RU",
    "Serbian": "sr-RS",
    "Sinhala": "si-LK",
    "Slovak": "sk-SK",
    "Slovenian": "sl-SI",
    "Spanish": "es-ES",
    "Swahili": "sw-KE",
    "Swedish": "sv-SE",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Turkish": "tr-TR",
    "Ukrainian": "uk-UA",
    "Urdu": "ur-PK",
    "Vietnamese": "vi-VN",
    "Yoruba": "yo-NG",
    "Zulu": "zu-ZA",
    "Hausa": "ha-NG",
    "Igbo": "ig-NG",
    "Kinyarwanda": "rw-RW",
    "Akan": "ak-GH",
    "Twi": "ak-GH",
    "Pidgin English": "pcm-NG",
    "Mandarin": "cmn-CN",
    "Cantonese": "yue-HK",
    "Arabic": "ar-SA",
    "Hindi": "hi-IN",
    "Bengali": "bn-IN",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Urdu": "ur-PK",
    "Punjabi": "pa-IN"
}


def normalize_language(lang_str: str) -> str:
    
    if not lang_str:
        return "en-US"
    return LANGUAGE_MAP.get(lang_str, lang_str)
